/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/
INSERT INTO Countries ([Name]) VALUES ('Algeria');
INSERT INTO Countries ([Name]) VALUES ('Angola');
INSERT INTO Countries ([Name]) VALUES ('Botswana');
INSERT INTO Countries ([Name]) VALUES ('Burkina Faso');
INSERT INTO Countries ([Name]) VALUES ('Burundi');
INSERT INTO Countries ([Name]) VALUES ('Cameroon');
INSERT INTO Countries ([Name]) VALUES ('Central African Republic');
INSERT INTO Countries ([Name]) VALUES ('Chad');
INSERT INTO Countries ([Name]) VALUES ('Congo DR');
INSERT INTO Countries ([Name]) VALUES ('Congo RO');
INSERT INTO Countries ([Name]) VALUES ('Egypt');
INSERT INTO Countries ([Name]) VALUES ('Eritrea');
INSERT INTO Countries ([Name]) VALUES ('Ethiopia');
INSERT INTO Countries ([Name]) VALUES ('Gambia');
INSERT INTO Countries ([Name]) VALUES ('Ghana');
INSERT INTO Countries ([Name]) VALUES ('Guinea');
INSERT INTO Countries ([Name]) VALUES ('Guinea-Bissau');
INSERT INTO Countries ([Name]) VALUES ('Ivory Coast');
INSERT INTO Countries ([Name]) VALUES ('Kenya');
INSERT INTO Countries ([Name]) VALUES ('Lesotho');
INSERT INTO Countries ([Name]) VALUES ('Liberia');
INSERT INTO Countries ([Name]) VALUES ('Libya');
INSERT INTO Countries ([Name]) VALUES ('Madagascar');
INSERT INTO Countries ([Name]) VALUES ('Malawi');
INSERT INTO Countries ([Name]) VALUES ('Mauritania');
INSERT INTO Countries ([Name]) VALUES ('Morocco');
INSERT INTO Countries ([Name]) VALUES ('Mozambique');
INSERT INTO Countries ([Name]) VALUES ('Namibia');
INSERT INTO Countries ([Name]) VALUES ('Niger');
INSERT INTO Countries ([Name]) VALUES ('Nigeria');
INSERT INTO Countries ([Name]) VALUES ('Rwanda');
INSERT INTO Countries ([Name]) VALUES ('Senegal');
INSERT INTO Countries ([Name]) VALUES ('Sierra Leone');
INSERT INTO Countries ([Name]) VALUES ('Somalia');
INSERT INTO Countries ([Name]) VALUES ('South Africa');
INSERT INTO Countries ([Name]) VALUES ('Sudan');
INSERT INTO Countries ([Name]) VALUES ('Suriname');
INSERT INTO Countries ([Name]) VALUES ('Swaziland');
INSERT INTO Countries ([Name]) VALUES ('Tanzania');
INSERT INTO Countries ([Name]) VALUES ('Togo');
INSERT INTO Countries ([Name]) VALUES ('Tunisia');
INSERT INTO Countries ([Name]) VALUES ('Western Sahara');
INSERT INTO Countries ([Name]) VALUES ('Yemen');
INSERT INTO Countries ([Name]) VALUES ('Zambia');
INSERT INTO Countries ([Name]) VALUES ('Zimbabwe');
INSERT INTO Countries ([Name]) VALUES ('Afghanistan');
INSERT INTO Countries ([Name]) VALUES ('Armenia');
INSERT INTO Countries ([Name]) VALUES ('Azerbaijan');
INSERT INTO Countries ([Name]) VALUES ('Bahrain');
INSERT INTO Countries ([Name]) VALUES ('Bangladesh');
INSERT INTO Countries ([Name]) VALUES ('Bhutan');
INSERT INTO Countries ([Name]) VALUES ('Cambodia');
INSERT INTO Countries ([Name]) VALUES ('China (Hong Kong)');
INSERT INTO Countries ([Name]) VALUES ('East Timor');
INSERT INTO Countries ([Name]) VALUES ('Georgia');
INSERT INTO Countries ([Name]) VALUES ('India');
INSERT INTO Countries ([Name]) VALUES ('Iran');
INSERT INTO Countries ([Name]) VALUES ('Iraq');
INSERT INTO Countries ([Name]) VALUES ('Japan');
INSERT INTO Countries ([Name]) VALUES ('Jordan');
INSERT INTO Countries ([Name]) VALUES ('Kazakhstan');
INSERT INTO Countries ([Name]) VALUES ('Kuwait');
INSERT INTO Countries ([Name]) VALUES ('Kyrgyzstan');
INSERT INTO Countries ([Name]) VALUES ('Malaysia');
INSERT INTO Countries ([Name]) VALUES ('Mongolia');
INSERT INTO Countries ([Name]) VALUES ('Myanmar');
INSERT INTO Countries ([Name]) VALUES ('Nepal');
INSERT INTO Countries ([Name]) VALUES ('North Korea');
INSERT INTO Countries ([Name]) VALUES ('Oman');
INSERT INTO Countries ([Name]) VALUES ('Pakistan');
INSERT INTO Countries ([Name]) VALUES ('Palestinian territories');
INSERT INTO Countries ([Name]) VALUES ('Papua New Guinea');
INSERT INTO Countries ([Name]) VALUES ('Qatar');
INSERT INTO Countries ([Name]) VALUES ('Saudi Arabia');
INSERT INTO Countries ([Name]) VALUES ('Singapore');
INSERT INTO Countries ([Name]) VALUES ('South Korea');
INSERT INTO Countries ([Name]) VALUES ('Sri Lanka');
INSERT INTO Countries ([Name]) VALUES ('Syria');
INSERT INTO Countries ([Name]) VALUES ('Taiwan');
INSERT INTO Countries ([Name]) VALUES ('Tajikistan');
INSERT INTO Countries ([Name]) VALUES ('Thailand');
INSERT INTO Countries ([Name]) VALUES ('Turkey');
INSERT INTO Countries ([Name]) VALUES ('Turkmenistan');
INSERT INTO Countries ([Name]) VALUES ('United Arab Emirates');
INSERT INTO Countries ([Name]) VALUES ('Uzbekistan');
INSERT INTO Countries ([Name]) VALUES ('Vietnam');
INSERT INTO Countries ([Name]) VALUES ('Albania');
INSERT INTO Countries ([Name]) VALUES ('Austria');
INSERT INTO Countries ([Name]) VALUES ('Belarus');
INSERT INTO Countries ([Name]) VALUES ('Belgium');
INSERT INTO Countries ([Name]) VALUES ('Bosnia and Herzegovina');
INSERT INTO Countries ([Name]) VALUES ('Bulgaria');
INSERT INTO Countries ([Name]) VALUES ('Croatia');
INSERT INTO Countries ([Name]) VALUES ('Cyprus');
INSERT INTO Countries ([Name]) VALUES ('Czech Republic');
INSERT INTO Countries ([Name]) VALUES ('Denmark');
INSERT INTO Countries ([Name]) VALUES ('Estonia');
INSERT INTO Countries ([Name]) VALUES ('Finland');
INSERT INTO Countries ([Name]) VALUES ('France');
INSERT INTO Countries ([Name]) VALUES ('Germany');
INSERT INTO Countries ([Name]) VALUES ('Greece');
INSERT INTO Countries ([Name]) VALUES ('Hungary');
INSERT INTO Countries ([Name]) VALUES ('Iceland');
INSERT INTO Countries ([Name]) VALUES ('Ireland');
INSERT INTO Countries ([Name]) VALUES ('Italy');
INSERT INTO Countries ([Name]) VALUES ('Latvia');
INSERT INTO Countries ([Name]) VALUES ('Lithuania');
INSERT INTO Countries ([Name]) VALUES ('Macedonia');
INSERT INTO Countries ([Name]) VALUES ('Moldova');
INSERT INTO Countries ([Name]) VALUES ('Montenegro');
INSERT INTO Countries ([Name]) VALUES ('Netherlands');
INSERT INTO Countries ([Name]) VALUES ('Poland');
INSERT INTO Countries ([Name]) VALUES ('Portugal');
INSERT INTO Countries ([Name]) VALUES ('Romania');
INSERT INTO Countries ([Name]) VALUES ('Russia');
INSERT INTO Countries ([Name]) VALUES ('Serbia');
INSERT INTO Countries ([Name]) VALUES ('Slovakia');
INSERT INTO Countries ([Name]) VALUES ('Slovenia');
INSERT INTO Countries ([Name]) VALUES ('Spain');
INSERT INTO Countries ([Name]) VALUES ('Sweden');
INSERT INTO Countries ([Name]) VALUES ('Switzerland');
INSERT INTO Countries ([Name]) VALUES ('Ukraine');
INSERT INTO Countries ([Name]) VALUES ('United Kingdom');
INSERT INTO Countries ([Name]) VALUES ('Bahamas');
INSERT INTO Countries ([Name]) VALUES ('Belize');
INSERT INTO Countries ([Name]) VALUES ('Canada');
INSERT INTO Countries ([Name]) VALUES ('Costa Rica');
INSERT INTO Countries ([Name]) VALUES ('Cuba');
INSERT INTO Countries ([Name]) VALUES ('Dominican Republic');
INSERT INTO Countries ([Name]) VALUES ('El Salvador');
INSERT INTO Countries ([Name]) VALUES ('Greenland');
INSERT INTO Countries ([Name]) VALUES ('Guatemala');
INSERT INTO Countries ([Name]) VALUES ('Haiti');
INSERT INTO Countries ([Name]) VALUES ('Honduras');
INSERT INTO Countries ([Name]) VALUES ('Jamaica');
INSERT INTO Countries ([Name]) VALUES ('Mexico');
INSERT INTO Countries ([Name]) VALUES ('Netherlands');
INSERT INTO Countries ([Name]) VALUES ('Nicaragua');
INSERT INTO Countries ([Name]) VALUES ('Panama');
INSERT INTO Countries ([Name]) VALUES ('Trinidad and Tobago');
INSERT INTO Countries ([Name]) VALUES ('United States (Puerto Rico)');
INSERT INTO Countries ([Name]) VALUES ('Australia');
INSERT INTO Countries ([Name]) VALUES ('Fiji');
INSERT INTO Countries ([Name]) VALUES ('New Zealand');
INSERT INTO Countries ([Name]) VALUES ('Argentina');
INSERT INTO Countries ([Name]) VALUES ('Bolivia');
INSERT INTO Countries ([Name]) VALUES ('Brazil');
INSERT INTO Countries ([Name]) VALUES ('Chile');
INSERT INTO Countries ([Name]) VALUES ('Colombia');
INSERT INTO Countries ([Name]) VALUES ('Ecuador');
INSERT INTO Countries ([Name]) VALUES ('Guyana');
INSERT INTO Countries ([Name]) VALUES ('Paraguay');
INSERT INTO Countries ([Name]) VALUES ('Peru');
INSERT INTO Countries ([Name]) VALUES ('Uruguay');
INSERT INTO Countries ([Name]) VALUES ('Venezuela');
